<a href="https://colab.research.google.com/github/akashkumar181/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#Array


In [ ]:
x=[1,2,3,4]#this is list
y=np.array(x)#this is array and converting x to array
y=np.array([1,2,3,4])#we can do like this also for converting list to array
print(y)
print(type(y))
print(y.ndim) #ndim tells which type of array like 1d,2d

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [ ]:
l=[]#empty list
for i in range(1,5): #we are taking input from 1 to 5
   value=int(input("Enter the value: "))
   l.append(value)
print(np.array(l))

Enter the value: 12
Enter the value: 2
Enter the value: 6
Enter the value: 8
['12' '2' '6' '8']


1D Array [1,2,3,4]
2d array [[1,2,3,5]]
3d array [[[4,5,6,8]]]

In [ ]:
arr2=np.array([[1,2,3],[333,78,99]])
print(arr2)
print(arr2.ndim)

[[  1   2   3]
 [333  78  99]]
2


In [ ]:
arr3=np.array([[[1,2,34,4],[3,4,5,6]]])
print(arr3)
print(arr3.ndim)

[[[ 1  2 34  4]
  [ 3  4  5  6]]]
3


In [ ]:
arn=np.array([1,2,3,4],ndmin=8)#it is creating 8d array
print(arn)
print(arn.ndim)

[[[[[[[[1 2 3 4]]]]]]]]
8


In [ ]:
l=[]
for i in range(1,5):
  value=int(input("Enter value: "))
  l.append(value)
arrn=np.array(l,ndmin=9)
print(arrn)
print(arrn.ndim)

Enter value: 2
Enter value: 5
Enter value: 7
Enter value: 9
[[[[[[[[[2 5 7 9]]]]]]]]]
9


Array filled with 0's


In [ ]:
x=int(input("Enter value: "))
arrr=np.zeros(x) #x denotes how much elements
arr=np.array(arrr,ndmin=3)

print(arr)
print(arr.ndim)

Enter value: 6
[[[0. 0. 0. 0. 0. 0.]]]
3


In [ ]:
arr=np.zeros((3,5))#it creates array of 3 by 5
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


Array filled with 1

In [ ]:
arr=np.ones(4)
print(arr)


[1. 1. 1. 1.]


Creating empty array

In [ ]:
y=np.empty(5)
print(y)

[0.   0.25 0.5  0.75 1.  ]


Range array


In [ ]:
x=np.arange(4)
print(x)

[0 1 2 3]


Diagonal element become 1

In [ ]:
arr=np.eye(3,6)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


%timeit work on one line of code but %%timeit work on whole program


Creating a specail array

In [ ]:
arr=np.linspace(0,80,num=8) #it takes value from 0 to 10 that is 8 elements
print(arr)

[ 0.         11.42857143 22.85714286 34.28571429 45.71428571 57.14285714
 68.57142857 80.        ]


rand():it gives random number between 0 to 1


In [ ]:
a=np.random.rand(5)
#a1=np.random.rand(5,8)
print(a)
#print(a1)

[0.78586703 0.4340272  0.79665876 0.05456417 0.2706178 ]
[[0.97099433 0.18528276 0.09681695 0.0061855  0.58816438 0.32379298
  0.87165925 0.83939321]
 [0.88327203 0.27653669 0.08988137 0.06172418 0.37639162 0.21668716
  0.29197902 0.85213643]
 [0.38838473 0.06104336 0.95583138 0.56668997 0.08431072 0.6423204
  0.8561709  0.44346476]
 [0.83321687 0.12832452 0.04931532 0.77780726 0.66338749 0.82067725
  0.10847526 0.47725053]
 [0.08235945 0.63868665 0.16646799 0.5887409  0.96483016 0.944586
  0.01436303 0.34083547]]


randn()=it creates random number that is close to 0 that is negative or positive

In [ ]:
x=np.random.randn(5)
print(x)

[-0.19167543 -2.01691791 -0.29941501  1.35989415  0.94154763]


ranf():it creates random number that is from[0.0,1.0) in which 1 is no included mtlb 0 to 1 jisme 1 nhi hoga

In [ ]:
x=np.random.ranf(6)
print(x)

[0.65882284 0.31593815 0.42872646 0.0706566  0.85965178 0.23285823]


randint():it creates any number between two range like 1 to 8 it gives number between 1 to 8

In [ ]:
v=np.random.randint(3,10,5)#3 is lower range and 10 is higher range 5 is how much number want
v1=np.random.randint(2,10,(6,7))
print(v)
print(v1)

[[4 9 8 4 3 8 2]
 [4 9 5 8 8 7 9]
 [2 6 9 4 6 4 3]
 [7 7 6 2 3 3 5]
 [9 8 2 2 7 9 6]
 [5 6 9 6 5 3 7]]


In [ ]:
x=int(input("Enter lower range: "))
y=int(input("Enter upper range: "))
no=int(input("Enter how much number want: "))
arr=np.random.randint(x,y,no)
print(arr)

Enter lower range: 0
Enter upper range: 1000
Enter how much number want: 79
[806 796 566 213 461 750  26 301 645 161 183 399 323 478 103 824 480 809
 480 785 771 153 646 519 533 324 656 140 277 182  10 848 390 664 146 147
 263 876 140 410 725 965  12 980 503 161 275 783 789 477 399 508 295 226
 327 901 868 161 662 708 945 826 844 843 199 590 222 998 582 373 856 768
 225 310  24 159 817 340  79]


#Shape

In [ ]:
var=np.array([[3,5,9],[6,9,9]])
print(var)
print(var.ndim)
print(var.shape) #it provide m=row*n=col type like 2*3

[[3 5 9]
 [6 9 9]]
2
(2, 3)


#Reshape

In [ ]:
var2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# x=var2.reshape(8,1)
# print(x)
x1=var2.reshape(2,3,2)
print(x1)
print(x1.ndim)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [ ]:
var2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# x=var2.reshape(8,1)
# print(x)
x1=var2.reshape(2,3,2)
print(x1)
print(x1.ndim)

one=x1.reshape(-1)#one d array
print(one)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]


#Airthmatic operation

Addition

In [ ]:
var=np.array([1,2,3,4])
varadd=var+3
print(varadd)

[4 5 6 7]


In [ ]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
varadd=var1+var2
varadd1=np.add(var1,var2)#function to add
varadd2=np.add(var1,3)#function to add
print(varadd)
print(varadd1)
print(varadd2)

[2 4 6 8]
[2 4 6 8]
[4 5 6 7]


Subtraction

In [ ]:
var=np.array([1,2,3,4])
varadd=var-3
print(varadd)

[-2 -1  0  1]


In [ ]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
varadd=var1-var2
print(varadd)

[0 0 0 0]


In [ ]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
varadd=var1*var2
print(varadd)

[ 1  4  9 16]


In [ ]:
var=np.array([1,2,3,4])
varadd=var*3
print(varadd)

[ 3  6  9 12]


In [ ]:
var=np.array([1,2,3,4])
varadd=var/3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [ ]:
var=np.array([1,2,3,4])
varadd=var%3
print(varadd)

[1 2 0 1]


#2D Array

In [ ]:
var1=np.array([[1,2,3,4]])
var2=np.array([[1,2,3,4]])
varadd=var1+var2
print(varadd)

[[2 4 6 8]]


In [ ]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
var2=np.array([[1,2,3,4],[5,6,7,8]])
varadd=var1-var2

print(varadd)

[[ 0  0  0  0]
 [-4 -4 -4 -4]]


In [ ]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
var2=np.array([[1,2,3,4],[5,6,7,8]])
varadd=var1/var2

print(varadd)

[[1.         1.         1.         1.        ]
 [0.2        0.33333333 0.42857143 0.5       ]]


In [ ]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
var2=np.array([[1,2,3,4],[5,6,7,8]])
varadd=var1%var2

print(varadd)

[[0 0 0 0]
 [1 2 3 4]]


In [ ]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
var2=np.array([[1,2,3,4],[5,6,7,8]])
varadd=var1/3

print(varadd)

[[0.33333333 0.66666667 1.         1.33333333]
 [0.33333333 0.66666667 1.         1.33333333]]


In [ ]:
%timeit [j**4 for j in range(1,9)]

829 ns ± 191 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


np.arange to create a array with power 4
with specific range


In [ ]:
var1=np.array([[1,2,3,4],[1,2,3,4]])
var2=np.array([[1,2,3,4],[5,6,7,8]])
varadd=np.reciprocal(var1) #ulta kar deta h

print(varadd)

[[1 0 0 0]
 [1 0 0 0]]


#Airthmatic Function

In [ ]:
var=np.array([9,2,3,4])
print("min: ",np.min(var),"Position: ",np.argmin(var));
print("max: ",np.max(var),"Position: ",np.argmax(var));


min:  2 Position:  1
max:  9 Position:  0


There are two types of axis =0,axis=1 and axis 0 work along column and axis=1 work along row

In [3]:
var1=np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis=0))

[2 1 3]


In [5]:
var1=np.array([[2,5,9],[7,8,9],[1,4,0]])
print(np.min(var1,axis=1))

[2 7 0]


In [6]:
var1=np.array([[2,5,9],[7,8,9],[1,4,0]])
print(np.min(var1,axis=1))
print("sqrt: ",np.sqrt(var1))

[2 7 0]
sqrt:  [[1.41421356 2.23606798 3.        ]
 [2.64575131 2.82842712 3.        ]
 [1.         2.         0.        ]]


In [8]:
var1=np.array([[2,1,9],[7,8,9],[1,4,0]])
#print(np.min(var1,axis=1))
print("sort: ",np.sort(var1))

sort:  [[1 2 9]
 [7 8 9]
 [0 1 4]]


In [12]:
var2=np.array([1,2,3,4])
print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))#in cumsum first digit as it after that it 1+2Nd digit previousresult+next no like this


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1  3  6 10]


#Broadcasting
1.Same Dimension of all array like ar1=m*n then another array also hv m*n
2.(3*1) (3*1) on comparing from right hand side at least 1 contains any of them

In [17]:
var1=np.array([1,2,34,6])
print(var1)
print(var1.shape)
var2=np.array([[1],[4],[5]])
print(var2.shape)
print(var1+var2)

(4,)
(3, 1)
[[ 2  3 35  7]
 [ 5  6 38 10]
 [ 6  7 39 11]]


#Indexing and Slicing

[[1,2],[1,2]]=0 for [1,2] and 1 for [1,2] for 2d


In [20]:
var1=np.array([1,2,3,4])
print(var1[2])
print(var1[-1])

3
4


In [22]:
var1=np.array([[1,2,3,4],[90,8,0,1]])
print(var1[0,1])# 0=first block and 1 is indexing of first block
print(var1[1,1])# 1=second block and 1 is indexing of second block

2
8


In [ ]:
var2=np.array([[[1,2,3],[4,6,8],[9,0,1]]])


In [ ]:
%timeit np.arange(1,9)**4

2.27 µs ± 79 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


1.Numpy is the fundamental package for scientific computing in python.
2.It is a python library that provides multidimensional array object,various derived objects.
#Advantage of using Numpy Arrays Over Phton list
1.consumes less memory
2.fast as compared to python list
3.convenient to use


