<a href="https://colab.research.google.com/github/akashkumar181/Numpy/blob/main/NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Combined Challenge
You are given the task of analyzing a dataset using NumPy. Follow the steps below to complete the challenge:

Create Data

Generate a 6×6 matrix of random integers between 10 and 100.

Extract the third row and store it in a separate variable.

Data Manipulation

Replace all even numbers in the matrix with -1.

Reshape the matrix into a 3×12 array.

Mathematical Operations

Compute the mean, median, and standard deviation of the reshaped array.

Normalize the matrix (scale values between 0 and 1).

Linear Algebra Operations

Extract the diagonal elements of the original 6×6 matrix.

Compute the dot product of the diagonal elements with themselves.

If the original matrix is invertible, find its inverse and determinant.

Boolean Operations

Create a mask that selects all values greater than the mean of the matrix.

Count how many values are greater than the mean.

Sorting & Unique Values

Find and print all unique values in the matrix.

Sort the matrix along each row in ascending order.

In [28]:
import numpy as pd

In [34]:
matrix=np.random.randint(10,100,(6,6))
print(matrix)

[[72 82 15 23 83 27]
 [37 19 63 13 45 97]
 [30 48 77 59 68 53]
 [28 49 85 16 44 30]
 [54 44 13 19 44 34]
 [12 23 88 46 84 66]]


In [39]:
thirdrow=matrix[3,:]
print(thirdrow)

[28 49 85 16 44 30]


In [47]:
matrix=np.where((matrix%2==0),-1,matrix)
print(matrix)

[[-1 -1 15 23 83 27]
 [37 19 63 13 45 97]
 [-1 -1 77 59 -1 53]
 [-1 49 85 -1 -1 -1]
 [-1 -1 13 19 -1 -1]
 [-1 23 -1 -1 -1 -1]]


In [48]:
re=matrix.reshape(3,12)
print(re)

[[-1 -1 15 23 83 27 37 19 63 13 45 97]
 [-1 -1 77 59 -1 53 -1 49 85 -1 -1 -1]
 [-1 -1 13 19 -1 -1 -1 23 -1 -1 -1 -1]]


In [51]:
y=np.median(matrix)
print(y)

6.0


In [53]:
y1=np.mean(matrix)
print(y1)

21.72222222222222


In [55]:
y3=np.std(matrix)
print(y3)

29.63163766343811


In [56]:
min=matrix.min()
max=np.max(matrix)
nor=(matrix-min)/(max-min)
print(nor)

[[0.         0.         0.16326531 0.24489796 0.85714286 0.28571429]
 [0.3877551  0.20408163 0.65306122 0.14285714 0.46938776 1.        ]
 [0.         0.         0.79591837 0.6122449  0.         0.55102041]
 [0.         0.51020408 0.87755102 0.         0.         0.        ]
 [0.         0.         0.14285714 0.20408163 0.         0.        ]
 [0.         0.24489796 0.         0.         0.         0.        ]]


In [57]:
dia=np.diagonal(matrix)
print(dia)

[-1 19 77 -1 -1 -1]


In [58]:
dotproduct=np.dot(dia,dia)
print(dotproduct)

6294


In [59]:
dotproduct=dia@dia
print(dotproduct)

6294


In [60]:
inv=np.linalg.inv(matrix)
print(inv)

[[-1.46118379e-02  2.84242977e-02 -4.25245630e-02  3.06378555e-05
   1.29217052e-01 -2.04122722e-02]
 [-1.20803363e-04  1.26843531e-03 -1.34673379e-03 -6.86425310e-05
   5.70728777e-03  4.27609984e-02]
 [ 3.65219469e-05 -3.83480443e-04  4.07152075e-04  1.16486594e-02
  -1.72545909e-03 -2.45556507e-02]
 [-1.70529398e-04  1.79055868e-03 -1.90108700e-03 -8.23643260e-03
   5.80565667e-02  1.85021536e-02]
 [ 1.18843352e-02  2.14480596e-04 -6.40055965e-03  2.68311449e-03
   5.19785343e-03 -5.42896140e-03]
 [ 8.30328025e-05 -8.71844426e-04  1.94441805e-02 -7.70475733e-03
  -5.94783942e-02  1.53976945e-02]]


In [61]:
det=np.linalg.det(matrix)
print(det)

-6150822143.999996


In [65]:
if det!=0:
  x=np.linalg.inv(matrix)
  print(x)
  print(det)

else:
  print("matrix is not invertiable")


[[-1.46118379e-02  2.84242977e-02 -4.25245630e-02  3.06378555e-05
   1.29217052e-01 -2.04122722e-02]
 [-1.20803363e-04  1.26843531e-03 -1.34673379e-03 -6.86425310e-05
   5.70728777e-03  4.27609984e-02]
 [ 3.65219469e-05 -3.83480443e-04  4.07152075e-04  1.16486594e-02
  -1.72545909e-03 -2.45556507e-02]
 [-1.70529398e-04  1.79055868e-03 -1.90108700e-03 -8.23643260e-03
   5.80565667e-02  1.85021536e-02]
 [ 1.18843352e-02  2.14480596e-04 -6.40055965e-03  2.68311449e-03
   5.19785343e-03 -5.42896140e-03]
 [ 8.30328025e-05 -8.71844426e-04  1.94441805e-02 -7.70475733e-03
  -5.94783942e-02  1.53976945e-02]]
-6150822143.999996


In [67]:
y=matrix[matrix>matrix.mean()]
print(y)

[23 83 27 37 63 45 97 77 59 53 49 85 23]


In [70]:
print(y.size)

13


In [71]:
y2=np.unique(matrix)
print(y2)

[-1 13 15 19 23 27 37 45 49 53 59 63 77 83 85 97]


In [72]:
x=np.sort(matrix,axis=1)
print(x)

[[-1 -1 15 23 27 83]
 [13 19 37 45 63 97]
 [-1 -1 -1 53 59 77]
 [-1 -1 -1 -1 49 85]
 [-1 -1 -1 -1 13 19]
 [-1 -1 -1 -1 -1 23]]
